name: Format

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

permissions:
  contents: read

jobs:
  opa-fmt:
    name: opa fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install OPA
        uses: open-policy-agent/setup-opa@v2
        with:
          version: latest

      - name: Check formatting
        run: opa fmt --fail --ignore .github .
